export const SET_SELECTED_TASK = "SET_SELECTED_TASK"
export const FETCH_TASKS = "FETCH_TASKS"
export const FETCH_TASK_BY_ID = "FETCH_TASK_BY_ID"
export const ADD_TASK="ADD_TASK"
export const UPDATE_TASK="UPDATE_TASK"
export const DELETE_TASK="DELETE_TASK"



