export const SET_SELECTED_TASK = "SET_SELECTED_TASK"
export const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST"
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS"
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE"

export const FETCH_TASK_BY_ID = "FETCH_TASK_BY_ID"
export const ADD_TASK="ADD_TASK"
export const UPDATE_TASK="UPDATE_TASK"
export const DELETE_TASK="DELETE_TASK"



